version: '3.8'

services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sustainafood
    ports:
      - "27017:27017" # Only needed if you want to access from host
    volumes:
      - mongo-data:/data/db
      - ./data/dump:/dump

  app:
    build: .
    image: localhost:8083/nodeapp:6.0
    container_name: back
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/sustainafood
    volumes:
      - .:/app
      - /app/node_modules

  front:
    image:  mariemtouzri1/soustaina_front:2
    ports:
      - "8070:80"
  # front:
  #   build: ./sustainafood-frontend # Indique à Docker Compose de construire à partir de ce dossier
  #   # image: mariemtouzri1/soustaina_front:2 # Commentez ou supprimez cette ligne
  #   ports:
  #     - "8070:80"
    depends_on: # Optionnel, mais peut aider à s'assurer que le backend est prêt
      - app

volumes:
  mongo-data:
