version: '3.8'

services:
  db:
    image: mongo:4.2
    container_name: db
    restart: always
    environment:
      MONGO_INITDB_DATABASE: sustainafood
    ports:
      - "27017:27017" # Only needed if you want to access from host
    volumes:
      - mongo-data:/data/db
      - ./data/dump:/dump

  app:
    build: .
    image: localhost:8083/nodeapp:6.0
    container_name: back
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - MONGODB_URI=mongodb://db:27017/sustainafood
    volumes:
      - .:/app
      - /app/node_modules

  # Service IA (Python/Flask) - UTILISE L'IMAGE DU REGISTRE
  ai_service:
    # Remplacez par le nom exact de l'image que votre pipeline Jenkins IA pousse
    # Exemple pour Docker Hub:
    image: walaammar/sustainafood-ai-service:latest
    # Exemple pour Nexus:
    # image: localhost:8083/sustainafood-ai-service:latest
    container_name: back_ai
    restart: unless-stopped
    ports:
      - "5001:5000" # Map le port 5001 de l'hôte au port 5000 du conteneur IA (où Flask/Gunicorn écoute)
    # PAS DE SECTION 'build:' ici car l'image est tirée du registre.
    environment:
      FLASK_ENV: production # Ou 'development' si nécessaire, mais 'production' est mieux pour Gunicorn
      # Ajoutez d'autres variables d'environnement si votre app.py en a besoin

  front:
    image: walaammar/soustaina_front:10
    ports:
      - "86:86"
    container_name: front
    restart: unless-stopped
    depends_on:
      - app
      - ai_service

  
volumes:
  mongo-data:
